export const MOCK_CLUSTERING = {
  id: "d",
  title: "cluster1",
  topics: [
    {
      id: "topic_1",
      title: "topic_1",
      documents: [
        {
          id: "mock-id-1",
          collection_id: "mock-collection-1",
          file_name: "example.pdf",
          source_file_path: "/files/example.pdf",
          file_type: "pdf",
          is_vectorized: true,
          is_graph_extracted: false,
          created_at: "2025-07-12T12:00:00Z",
          updated_at: "2025-07-12T12:00:00Z",
          created_by: "user1",
          updated_by: "user1",
        },
        {
          id: "mock-id-2",
          collection_id: "mock-collection-1",
          file_name: "document_A.docx",
          source_file_path: "/files/document_A.docx",
          file_type: "docx",
          is_vectorized: true,
          is_graph_extracted: false,
          created_at: "2025-07-12T12:05:00Z",
          updated_at: "2025-07-12T12:05:00Z",
          created_by: "user2",
          updated_by: "user2",
        },
      ],
    },
    {
      id: "topic_2",
      title: "topic_2_finance",
      documents: [
        {
          id: "mock-id-3",
          collection_id: "mock-collection-2",
          file_name: "report_Q1_2025.xlsx",
          source_file_path: "/files/report_Q1_2025.xlsx",
          file_type: "xlsx",
          is_vectorized: true,
          is_graph_extracted: true,
          created_at: "2025-07-12T12:10:00Z",
          updated_at: "2025-07-12T12:10:00Z",
          created_by: "user1",
          updated_by: "user1",
        },
        {
          id: "mock-id-4",
          collection_id: "mock-collection-2",
          file_name: "financial_statement.pdf",
          source_file_path: "/files/financial_statement.pdf",
          file_type: "pdf",
          is_vectorized: true,
          is_graph_extracted: false,
          created_at: "2025-07-12T12:15:00Z",
          updated_at: "2025-07-12T12:15:00Z",
          created_by: "user3",
          updated_by: "user3",
        },
      ],
    },
    {
      id: "topic_3",
      title: "topic_3_legal",
      documents: [
        {
          id: "mock-id-5",
          collection_id: "mock-collection-3",
          file_name: "contract_draft.docx",
          source_file_path: "/files/contract_draft.docx",
          file_type: "docx",
          is_vectorized: true,
          is_graph_extracted: false,
          created_at: "2025-07-12T12:20:00Z",
          updated_at: "2025-07-12T12:20:00Z",
          created_by: "user4",
          updated_by: "user4",
        },
      ],
    },
  ],
  documents: [
    {
      id: "mock-id-1",
      collection_id: "mock-collection-1",
      file_name: "example.pdf",
      source_file_path: "/files/example.pdf",
      file_type: "pdf",
      is_vectorized: true,
      is_graph_extracted: false,
      created_at: "2025-07-12T12:00:00Z",
      updated_at: "2025-07-12T12:00:00Z",
      created_by: "user1",
      updated_by: "user1",
    },
    {
      id: "mock-id-2",
      collection_id: "mock-collection-1",
      file_name: "document_A.docx",
      source_file_path: "/files/document_A.docx",
      file_type: "docx",
      is_vectorized: true,
      is_graph_extracted: false,
      created_at: "2025-07-12T12:05:00Z",
      updated_at: "2025-07-12T12:05:00Z",
      created_by: "user2",
      updated_by: "user2",
    },
    {
      id: "mock-id-3",
      collection_id: "mock-collection-2",
      file_name: "report_Q1_2025.xlsx",
      source_file_path: "/files/report_Q1_2025.xlsx",
      file_type: "xlsx",
      is_vectorized: true,
      is_graph_extracted: true,
      created_at: "2025-07-12T12:10:00Z",
      updated_at: "2025-07-12T12:10:00Z",
      created_by: "user1",
      updated_by: "user1",
    },
    {
      id: "mock-id-4",
      collection_id: "mock-collection-2",
      file_name: "financial_statement.pdf",
      source_file_path: "/files/financial_statement.pdf",
      file_type: "pdf",
      is_vectorized: true,
      is_graph_extracted: false,
      created_at: "2025-07-12T12:15:00Z",
      updated_at: "2025-07-12T12:15:00Z",
      created_by: "user3",
      updated_by: "user3",
    },
    {
      id: "mock-id-5",
      collection_id: "mock-collection-3",
      file_name: "contract_draft.docx",
      source_file_path: "/files/contract_draft.docx",
      file_type: "docx",
      is_vectorized: true,
      is_graph_extracted: false,
      created_at: "2025-07-12T12:20:00Z",
      updated_at: "2025-07-12T12:20:00Z",
      created_by: "user4",
      updated_by: "user4",
    },
  ],
};
