import { MOCK_DOCUMENTS } from "./documents";

export const MOCK_CLUSTERING = {
  id: "cluster-A",
  title: "Knowledge_Cluster",
  topics: [
    {
      id: "topic_AI",
      title: "Artificial Intelligence",
      documents: [
        {
          id: "doc-001",
          collection_id: "collection-AI",
          file_name: "AI_Research_Survey.pdf",
          source_file_path: "/files/AI_Research_Survey.pdf",
          file_type: ".pdf",
          is_vectorized: true,
          is_graph_extracted: true,
          created_at: "2025-07-10T10:00:00Z",
          updated_at: "2025-07-10T10:30:00Z",
          created_by: "user_alpha",
          updated_by: "user_alpha",
        },
        {
          id: "doc-005",
          collection_id: "collection-ML",
          file_name: "training_data.csv",
          source_file_path: "/files/training_data.csv",
          file_type: ".csv",
          is_vectorized: true,
          is_graph_extracted: false,
          created_at: "2025-07-10T13:00:00Z",
          updated_at: "2025-07-10T13:20:00Z",
          created_by: "user_epsilon",
          updated_by: "user_epsilon",
        },
      ],
    },
    {
      id: "topic_Business",
      title: "Business Strategy",
      documents: [
        {
          id: "doc-002",
          collection_id: "collection-Business",
          file_name: "Product_Roadmap_2025.pptx",
          source_file_path: "/files/Product_Roadmap_2025.pptx",
          file_type: ".pptx",
          is_vectorized: true,
          is_graph_extracted: false,
          created_at: "2025-07-11T11:00:00Z",
          updated_at: "2025-07-11T11:45:00Z",
          created_by: "user_beta",
          updated_by: "user_beta",
        },
      ],
    },
    {
      id: "topic_Finance",
      title: "Financial Reports",
      documents: [
        {
          id: "doc-003",
          collection_id: "collection-Finance",
          file_name: "Q3_Financials.xlsx",
          source_file_path: "/files/Q3_Financials.xlsx",
          file_type: ".xlsx",
          is_vectorized: true,
          is_graph_extracted: true,
          created_at: "2025-07-09T08:00:00Z",
          updated_at: "2025-07-09T08:20:00Z",
          created_by: "user_gamma",
          updated_by: "user_gamma",
        },
      ],
    },
    {
      id: "topic_Legal",
      title: "Contracts",
      documents: [
        {
          id: "doc-004",
          collection_id: "collection-Legal",
          file_name: "Team_Contract.pdf",
          source_file_path: "/files/Team_Contract.docx",
          file_type: ".docx",
          is_vectorized: false,
          is_graph_extracted: false,
          created_at: "2025-07-12T12:00:00Z",
          updated_at: "2025-07-12T12:30:00Z",
          created_by: "user_delta",
          updated_by: "user_delta",
        },
        {
          id: "doc-006",
          collection_id: "collection-Legal",
          file_name: "Team_Contract.csv",
          source_file_path: "/files/Team_Contract.docx",
          file_type: ".docx",
          is_vectorized: false,
          is_graph_extracted: false,
          created_at: "2025-07-12T12:00:00Z",
          updated_at: "2025-07-12T12:30:00Z",
          created_by: "user_delta",
          updated_by: "user_delta",
        },
      ],
    },
  ],
  documents: MOCK_DOCUMENTS,
};
