export const MOCK_DOCUMENTS = [
  {
    id: "doc-001",
    file_name: "AI_Research_Survey.pdf",
    source_file_path: "/files/AI_Research_Survey.pdf",
    file_type: ".pdf",
    collection_id: "collection-AI",
    is_vectorized: true,
    is_graph_extracted: true,
    created_at: "2025-07-10T10:00:00Z",
    updated_at: "2025-07-10T10:30:00Z",
    created_by: "user_alpha",
    updated_by: "user_alpha",
  },
  {
    id: "doc-002",
    file_name: "Product_Roadmap_2025.pptx",
    source_file_path: "/files/Product_Roadmap_2025.pptx",
    file_type: ".pptx",
    collection_id: "collection-Business",
    is_vectorized: true,
    is_graph_extracted: false,
    created_at: "2025-07-11T11:00:00Z",
    updated_at: "2025-07-11T11:45:00Z",
    created_by: "user_beta",
    updated_by: "user_beta",
  },
  {
    id: "doc-003",
    file_name: "Q3_Financials.xlsx",
    source_file_path: "/files/Q3_Financials.xlsx",
    file_type: ".xlsx",
    collection_id: "collection-Finance",
    is_vectorized: true,
    is_graph_extracted: true,
    created_at: "2025-07-09T08:00:00Z",
    updated_at: "2025-07-09T08:20:00Z",
    created_by: "user_gamma",
    updated_by: "user_gamma",
  },
  {
    id: "doc-004",
    file_name: "Team_Contract.docx",
    source_file_path: "/files/Team_Contract.docx",
    file_type: ".docx",
    collection_id: "collection-Legal",
    is_vectorized: false,
    is_graph_extracted: false,
    created_at: "2025-07-12T12:00:00Z",
    updated_at: "2025-07-12T12:30:00Z",
    created_by: "user_delta",
    updated_by: "user_delta",
  },
  {
    id: "doc-005",
    file_name: "training_data.csv",
    source_file_path: "/files/training_data.csv",
    file_type: ".csv",
    collection_id: "collection-ML",
    is_vectorized: true,
    is_graph_extracted: false,
    created_at: "2025-07-10T13:00:00Z",
    updated_at: "2025-07-10T13:20:00Z",
    created_by: "user_epsilon",
    updated_by: "user_epsilon",
  },
  {
    id: "doc-006",
    file_name: "project_notes.txt",
    source_file_path: "/files/project_notes.txt",
    file_type: ".txt",
    collection_id: "collection-Notes",
    is_vectorized: false,
    is_graph_extracted: false,
    created_at: "2025-07-12T09:00:00Z",
    updated_at: "2025-07-12T09:05:00Z",
    created_by: "user_zeta",
    updated_by: "user_zeta",
  },
  {
    id: "doc-007",
    file_name: "app_config.json",
    source_file_path: "/files/app_config.json",
    file_type: ".json",
    collection_id: "collection-Config",
    is_vectorized: false,
    is_graph_extracted: false,
    created_at: "2025-07-12T10:00:00Z",
    updated_at: "2025-07-12T10:15:00Z",
    created_by: "user_eta",
    updated_by: "user_eta",
  },
  {
    id: "doc-008",
    file_name: "landing_page.html",
    source_file_path: "/files/landing_page.html",
    file_type: ".html",
    collection_id: "collection-Web",
    is_vectorized: true,
    is_graph_extracted: false,
    created_at: "2025-07-11T16:00:00Z",
    updated_at: "2025-07-11T16:10:00Z",
    created_by: "user_theta",
    updated_by: "user_theta",
  },
];
