"""Add clustering status

Revision ID: 11879685e147
Revises: fa459aee9e4e
Create Date: 2025-08-01 15:53:11.995328

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11879685e147"
down_revision: Union[str, Sequence[str], None] = "fa459aee9e4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clustering",
        sa.Column(
            "status",
            sa.Enum("idle", "processing", name="clusteringstatus", native_enum=False),
            server_default="idle",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clustering", "status")
    # ### end Alembic commands ###
