"""add more chunk details

Revision ID: 79a10daee625
Revises: 20c652719737
Create Date: 2025-07-08 09:10:55.187577

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = "79a10daee625"
down_revision: Union[str, Sequence[str], None] = "20c652719737"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chunk", sa.Column("start_char", sa.Integer(), nullable=True))
    op.add_column("chunk", sa.Column("token_count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chunk", "token_count")
    op.drop_column("chunk", "start_char")
    # ### end Alembic commands ###
