"""clustertopic use document foreign key

Revision ID: 9ec9f9027d34
Revises: 2c80da6c8031
Create Date: 2025-07-30 13:23:29.221737

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = "9ec9f9027d34"
down_revision: Union[str, Sequence[str], None] = "2c80da6c8031"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "clustering_child", "document", ["target"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "clustering_child", type_="foreignkey")
    # ### end Alembic commands ###
