"""Add chats status

Revision ID: d630aa20fb3b
Revises: 2c80da6c8031
Create Date: 2025-07-30 13:12:32.484741

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d630aa20fb3b"
down_revision: Union[str, Sequence[str], None] = "2c80da6c8031"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collection_chat",
        sa.Column(
            "status",
            sa.Enum(
                "new_session",
                "awaiting_user_input",
                "processing_input",
                "responding",
                "response_complete",
                "error_state",
                "session_ended",
                name="chatstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collection_chat", "status")
    # ### end Alembic commands ###
