"""add node, edges connections

Revision ID: ddd85fd69472
Revises: 11879685e147
Create Date: 2025-08-02 20:44:11.120843

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ddd85fd69472"
down_revision: Union[str, Sequence[str], None] = "11879685e147"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "collection_chat", "status", existing_type=sa.VARCHAR(length=19), nullable=False
    )
    op.create_foreign_key(
        None, "document_edge", "document_node", ["source"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "document_edge", "document_node", ["target"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "document_edge", type_="foreignkey")
    op.drop_constraint(None, "document_edge", type_="foreignkey")
    op.alter_column(
        "collection_chat", "status", existing_type=sa.VARCHAR(length=19), nullable=True
    )
    # ### end Alembic commands ###
