"""add document summary, file_size, ingestion status

Revision ID: f3928c388893
Revises: 9c2745e14cf3
Create Date: 2025-07-28 17:04:47.969399

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = "f3928c388893"
down_revision: Union[str, Sequence[str], None] = "9c2745e14cf3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("document", sa.Column("summary", sa.Text(), nullable=True))
    op.add_column("document", sa.Column("file_size", sa.Integer(), nullable=True))
    ingestion_status = sa.Enum(
        "pending", "processing", "ready", "failed", name="ingestionstatus"
    )
    ingestion_status.create(op.get_bind(), checkfirst=True)
    op.add_column("document", sa.Column("status", ingestion_status, nullable=True))
    op.execute("UPDATE document SET status='pending' WHERE status IS NULL")
    op.alter_column("document", "status", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document", "status")
    op.drop_column("document", "file_size")
    op.drop_column("document", "summary")
    op.drop_column("document", "description")
    # ### end Alembic commands ###
