"""fix_collection_permissions_nullable_constraints

Revision ID: f6017c9a5a0a
Revises: 7814de9a2166
Create Date: 2025-08-01 15:19:10.757776

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6017c9a5a0a"
down_revision: Union[str, Sequence[str], None] = "7814de9a2166"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "collection_permission", "granted_by", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "collection_permission_log",
        "performed_by",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "collection_permission_log",
        "performed_by",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "collection_permission", "granted_by", existing_type=sa.TEXT(), nullable=False
    )
    # ### end Alembic commands ###
