"""Add collection status

Revision ID: fa459aee9e4e
Revises: f6017c9a5a0a
Create Date: 2025-08-01 15:47:42.228350

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa459aee9e4e"
down_revision: Union[str, Sequence[str], None] = "f6017c9a5a0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collection",
        sa.Column(
            "status",
            sa.Enum("idle", "processing", name="collectionstatus", native_enum=False),
            server_default="idle",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collection", "status")
    # ### end Alembic commands ###
